#!/usr/bin/env bash
# Copyright The Orca Authors
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail
cd "$(dirname "$0")/.."

uv python install
uv sync --all-groups
uv export -o requirements-dev.lock --no-hashes --all-groups
